### ISSUE TITLE
License

### ISSUE THREAD

**Issue by DaanVanYperen** [cypai/wf#4]
Hi there! Found your project while scouting for interesting artemis-odb projects, Was wondering what kind of license your source is under! Would you mind adding a license file?

**Comment by cypai** [comment]
Hey there, I'm surprised anyone actually found this project :)

Unfortunately I'm planning on stopping work on it since it's too ambitious and barely playable even after a year's worth of spare time development. I have added the Apache license though.

Code is free to use and modify. Maybe someone will find the structure or code useful at some point.

Out of curiosity, what made this project interesting for you?

**Comment by DaanVanYperen** [comment]
I'm one of the contributors of artemis-odb. It's fun to take a peek under the hood and see how developers use the framework. We've got a gallery on the wiki as well, that's why I asked for the license. There might always be someone who can salvage some ideas!

Thanks for adding the license!
